"""Add checkout size selection fields

Revision ID: 1c7f82702348
Revises: 6efcf16d4fa7
Create Date: 2026-07-29 14:21:06.135921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7f82702348'
down_revision = '6efcf16d4fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printify_size_variant_map', sa.Text(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_size', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('printify_variant_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('printify_variant_id')
        batch_op.drop_column('selected_size')

    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.drop_column('printify_size_variant_map')

    # ### end Alembic commands ###
