"""Remove Instagram drop fields

Revision ID: 39fca36a1fba
Revises: 72823dee39f1
Create Date: 2026-07-30 14:42:15.492623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fca36a1fba'
down_revision = '72823dee39f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.drop_column('instagram_media_id')
        batch_op.drop_column('instagram_permalink')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram_permalink', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_media_id', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
