"""Add drop mockup image urls

Revision ID: 656e5580371c
Revises: 6675d2f1dd95
Create Date: 2026-07-24 13:10:56.325033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656e5580371c'
down_revision = '6675d2f1dd95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mockup_image_urls', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.drop_column('mockup_image_urls')

    # ### end Alembic commands ###
