"""Add monthly drop integration fields

Revision ID: 6675d2f1dd95
Revises: 3272159bed14
Create Date: 2026-07-08 17:05:17.384146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6675d2f1dd95'
down_revision = '3272159bed14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=50), server_default='t-shirt', nullable=False))
        batch_op.add_column(sa.Column('shirt_color', sa.String(length=80), server_default='Black', nullable=False))
        batch_op.add_column(sa.Column('printify_product_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('printify_variant_ids', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('instagram_media_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('instagram_permalink', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drop', schema=None) as batch_op:
        batch_op.drop_column('instagram_permalink')
        batch_op.drop_column('instagram_media_id')
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_product_id')
        batch_op.drop_column('printify_variant_ids')
        batch_op.drop_column('printify_product_id')
        batch_op.drop_column('shirt_color')
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###
