"""Add Printify fulfillment fields

Revision ID: 72823dee39f1
Revises: 1c7f82702348
Create Date: 2026-07-30 13:11:34.712470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72823dee39f1'
down_revision = '1c7f82702348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printify_status', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('printify_last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('printify_submitted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('printify_submitted_at')
        batch_op.drop_column('printify_last_error')
        batch_op.drop_column('printify_status')

    # ### end Alembic commands ###
